# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

timeout: 3600s # 1-hr
tags:
  - delivery-platform
  - delivery-platform-acm
steps:
- name: 'gcr.io/${PROJECT_ID}/delivery-platform-installer'
  id: 'apply-acm'
  entrypoint: 'bash'
  args:
  - '-xe'
  - '-c'
  - |
    sed "s/YOUR_PROJECT_ID/${PROJECT_ID}/g" backend.tmpl > backend.tf
    sed "s/YOUR_PROJECT_ID/${PROJECT_ID}/g" remote_state.tmpl > remote_state.tf
    sed "s/YOUR_PROJECT_ID/${PROJECT_ID}/g" terraform.tmpl > terraform.tfvars
    sed -i "s|CONFIG_REPO|${_CLUSTER_CONFIG_REPO}|g" terraform.tfvars
    sed -i "s|BRANCH|${_BRANCH}|g" terraform.tfvars
    sed -i "s|DEV_PATH|${_DEV_PATH}|g" terraform.tfvars
    sed -i "s|STAGE_PATH|${_STAGE_PATH}|g" terraform.tfvars
    sed -i "s|PROD_PATH|${_PROD_PATH}|g" terraform.tfvars

    #export TF_LOG="ERROR"

    terraform init
    terraform plan -var-file="terraform.tfvars" -out=terraform.tfplan
    terraform apply -auto-approve terraform.tfplan

substitutions:
    _CLUSTER_CONFIG_REPO: https://github.com/GoogleCloudPlatform/csp-config-management/
    _BRANCH: 1.0.0
    _DEV_PATH: foo-corp
    _STAGE_PATH: foo-corp
    _PROD_PATH: foo-corp
